#!/usr/bin/bash

if [ $# -eq 0 ];
then
	echo "You need a name for your project!"
	exit 1
fi

PROJECT_NAME=$1
if [ -d "./${PROJECT_NAME}" ]
then
	echo "Directory already exists. Aborting."
	exit 1
fi

mkdir $PROJECT_NAME
cd $PROJECT_NAME
touch deps.edn
echo "{}" > deps.edn
mkdir src
cd src
touch core.clj
cat > core.clj << EOM
(ns core)

(defn -main [opts]
  (println "Hello, World!"))
EOM

echo "${PROJECT_NAME} directory created."
echo "try this:"
echo "cd ${PROJECT_NAME}"
echo "clj -X core/-main"
