#!/usr/bin/bash 
#Stops every active Taskwarrior task in one go

ACTIVE_TASKS="$(task active)"
NUM_ACTIVE_TASKS=`echo "$ACTIVE_TASKS" | awk 'END{print}' | awk '{print $1}'`
ROW_END=$((`echo "$ACTIVE_TASKS" | awk 'END{print NR}'` - 1))

if [ $(($NUM_ACTIVE_TASKS)) -eq 0 ]
then 
	echo "No tasks are currently active"
	exit 0
else 
	ROWS=`echo "$ACTIVE_TASKS"  | awk -v e=$ROW_END 'FNR>=4 && FNR<=e'`
	ACTIVE_IDS=`echo "$ROWS" | awk '{if ($1 == $1+0) print $1}'`
	for ID in $ACTIVE_IDS
	do
		task $ID stop
	done
fi 
